## Data Encoding

1. Nominal/OHE Encoding

2.Label & Ordinal Encoding

3. Target Guided Ordinal Encoding

## Nominal / OHE Encoding

It is a technique used to represent categorical data as numerical data, which is more suitable for ML algorithms. In this technique each category is represented as binary vector where each bit corresponds to a unique category. For example if we have categorical variable 'color' with three possible values (red, green,blue) we can represent it in ohe as follows:
1. Red (1,0,0)

2. Green (0,1,0)

3. Blue (0,0,1)

In [21]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [22]:
## create a sample dataframe
df = pd.DataFrame({'color': ['red', 'blue', 'green','green', 'red', 'blue']})

In [23]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [24]:
## create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [25]:
## perform fit and transform
encoded_data = encoder.fit_transform(df[['color']]).toarray()
encoded_data

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [26]:
import pandas as pd
encoder_df=pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out(['color']))
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [27]:
## for new data
encoder.transform([['red']]).toarray()

e:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [28]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

### Label Encoding

Label encoding is a technique used to convert categorical data into numerical data by assigning a unique integer to each category. For example if we have a categorical variable 'color' with three possible values (red, green, blue) we can represent it in label encoding as follows:
1. Red (0)
2. Green (1)
3. Blue (2)

In [29]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [30]:
from sklearn.preprocessing import LabelEncoder

In [33]:
label_encoder = LabelEncoder()
color_encoded= label_encoder.fit_transform(df[['color']])
color_encoded

e:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [34]:
label_encoder.transform([['red']])

e:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [16]:
label_encoder.transform([['blue']])

e:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

## Ordinal Encoding

Ordinal encoding is a technique used to convert categorical data into numerical data by assigning a unique integer to each category based on their order or rank. For example if we have a categorical variable 'size' with three possible values (small, medium, large) we can represent it in ordinal encoding as follows:
1. Small (0)
2. Medium (1)
3. Large (2)

In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
df=pd.DataFrame({'size': ['small', 'medium', 'large','medium', 'small', 'large']})

In [38]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [40]:
ordinal_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])
size_encoded = ordinal_encoder.fit_transform(df[['size']])
size_encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [41]:
ordinal_encoder.transform([['medium']])

e:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

## Target Guided Ordinal Encoding
Target guided ordinal encoding is a technique used to convert categorical data into numerical data by assigning a unique integer to each category based on the mean of the target variable for that category. For example if we have a categorical variable 'color' with three possible values (red, green, blue) and a target variable 'price' we can represent it in target guided ordinal encoding as follows:
1. Red (mean price for red)
2. Green (mean price for green)
3. Blue (mean price for blue)

In [45]:
import pandas as pd

df=pd.DataFrame({
    'city': ['New York', 'London', 'Paris','Tokyo', 'New York', 'Paris'],
'price':[100, 200, 150, 120, 180, 130]})

In [46]:
df

       city  price
0  New York    100
1    London    200
2     Paris    150
3     Tokyo    120
4  New York    180
5     Paris    130

In [48]:
mean_prices = df.groupby('city')['price'].mean().to_dict()

In [49]:
mean_prices

{'London': 200.0, 'New York': 140.0, 'Paris': 140.0, 'Tokyo': 120.0}

In [50]:
df['city_encoded'] = df['city'].map(mean_prices)

In [51]:
df

       city  price  city_encoded
0  New York    100         140.0
1    London    200         200.0
2     Paris    150         140.0
3     Tokyo    120         120.0
4  New York    180         140.0
5     Paris    130         140.0

In [52]:
df[['price', 'city_encoded']]

   price  city_encoded
0    100         140.0
1    200         200.0
2    150         140.0
3    120         120.0
4    180         140.0
5    130         140.0