### Handling Imbalanced Dataset

1. Up Sampling ( increasing data point of minority)

2.Down sampling (decreasing data point of majority)

In [3]:
import numpy as np
import pandas as pd

## set the random seed for reproducibility
np.random.seed(123)

## create a sample dataframe with two classes
n_samples = 1000
class_0_ratio=0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0, n_class_1

(900, 100)

In [5]:
## create my dataframe with imbalanced classes
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=1, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=1, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [8]:
df=pd.concat([class_0, class_1]).reset_index(drop=True)

In [9]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [10]:
df.tail()

     feature1  feature2  target
995  0.376371  1.845701       1
996  1.239810 -0.119923       1
997  0.131760  0.640703       1
998  1.902006 -0.609695       1
999  1.697490  1.013570       1

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## upsampling

In [12]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [13]:
from sklearn.utils import resample

df_minority_upsample=df_minority_upsampled = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)

In [14]:
df_minority_upsample.shape

(900, 3)

In [15]:
df_minority_upsample.head()

     feature1  feature2  target
951  0.125854  0.843917       1
992  1.196570  0.397425       1
914  0.932170  1.998053       1
971  1.272825  2.034197       1
960  1.870056  0.550485       1

In [16]:
df_upsampled=pd.concat([df_majority, df_minority_upsample])

In [17]:
df_upsampled

     feature1  feature2  target
0   -1.085631  0.551302       0
1    0.997345  0.419589       0
2    0.282978  1.815652       0
3   -1.506295 -0.252750       0
4   -0.578600 -0.292004       0
..        ...       ...     ...
952  0.188902  1.189189       1
965  2.919526  0.980541       1
976  1.810326  2.604614       1
942  2.621531  1.168229       1
974  0.160887  1.489203       1

[1800 rows x 3 columns]

In [18]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [19]:
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=1, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=1, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [20]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [21]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [30]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,  n_samples=len(df_minority), random_state=42)

In [31]:
df_majority_downsampled.shape

(100, 3)

In [32]:
df_downsampled=pd.concat([df_majority_downsampled, df_minority])

In [33]:
df_downsampled

     feature1  feature2  target
102  0.712265  0.718151       0
435  1.199988  0.574621       0
860  0.304515 -0.759475       0
270 -1.213385  0.675504       0
106  0.179549 -0.202659       0
..        ...       ...     ...
995  0.376371  1.845701       1
996  1.239810 -0.119923       1
997  0.131760  0.640703       1
998  1.902006 -0.609695       1
999  1.697490  1.013570       1

[200 rows x 3 columns]

In [34]:
df_downsampled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64